### ISSUE TITLE
output "leaner" CSS (include only what is needed)

### ISSUE THREAD

**Issue by jason-s** [anaconda-graveyard/nbpresent#80]
If I click Download as Presentation (.html) in Jupyter, I get 11000 lines of CSS; is there any way to just include the .css that is actually used? Somehow this seems excessive.

**Comment by bollwyvl** [comment]
Yeah. You are getting this any time you use the notebook on, say, nbviewer... it just does it in multiple files. Among the challenges: one of the goals of nbpresent is to end up with archival, offline assets. So we are stuck putting the style in the file. Further, since notebooks are so dynamic, we basically have to ship something as close to the authoring environment as possible. 

Confounding this, the notebook doesn't make every user install a front-end asset build chain (css, js, etc.) so we pretty much have to ship the whole kitchen sink. Doing "live" builds would theoretically make this better. It seems increasingly likely that a future notebook/nbconvert may include several transpilers that would more capable of performing these calculations, but for now, I don't think it's going to change!
